// source: pbf/update/search.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.update.SearchI', null, global);
goog.exportSymbol('proto.update.SearchI.Filter', null, global);
goog.exportSymbol('proto.update.SearchI.Filter.Chunking', null, global);
goog.exportSymbol('proto.update.SearchI.Filter.Property', null, global);
goog.exportSymbol('proto.update.SearchO', null, global);
goog.exportSymbol('proto.update.SearchO.Filter', null, global);
goog.exportSymbol('proto.update.SearchO.Filter.Chunking', null, global);
goog.exportSymbol('proto.update.SearchO.Result', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.update.SearchI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.update.SearchI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.update.SearchI.displayName = 'proto.update.SearchI';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.update.SearchI.Filter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.update.SearchI.Filter.repeatedFields_, null);
};
goog.inherits(proto.update.SearchI.Filter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.update.SearchI.Filter.displayName = 'proto.update.SearchI.Filter';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.update.SearchI.Filter.Chunking = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.update.SearchI.Filter.Chunking, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.update.SearchI.Filter.Chunking.displayName = 'proto.update.SearchI.Filter.Chunking';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.update.SearchI.Filter.Property = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.update.SearchI.Filter.Property, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.update.SearchI.Filter.Property.displayName = 'proto.update.SearchI.Filter.Property';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.update.SearchO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.update.SearchO.repeatedFields_, null);
};
goog.inherits(proto.update.SearchO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.update.SearchO.displayName = 'proto.update.SearchO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.update.SearchO.Filter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.update.SearchO.Filter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.update.SearchO.Filter.displayName = 'proto.update.SearchO.Filter';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.update.SearchO.Filter.Chunking = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.update.SearchO.Filter.Chunking, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.update.SearchO.Filter.Chunking.displayName = 'proto.update.SearchO.Filter.Chunking';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.update.SearchO.Result = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.update.SearchO.Result, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.update.SearchO.Result.displayName = 'proto.update.SearchO.Result';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.update.SearchI.prototype.toObject = function(opt_includeInstance) {
  return proto.update.SearchI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.update.SearchI} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchI.toObject = function(includeInstance, msg) {
  var f, obj = {
    filter: (f = msg.getFilter()) && proto.update.SearchI.Filter.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.update.SearchI}
 */
proto.update.SearchI.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.update.SearchI;
  return proto.update.SearchI.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.update.SearchI} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.update.SearchI}
 */
proto.update.SearchI.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.update.SearchI.Filter;
      reader.readMessage(value,proto.update.SearchI.Filter.deserializeBinaryFromReader);
      msg.setFilter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.update.SearchI.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.update.SearchI.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.update.SearchI} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchI.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilter();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.update.SearchI.Filter.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.update.SearchI.Filter.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.update.SearchI.Filter.prototype.toObject = function(opt_includeInstance) {
  return proto.update.SearchI.Filter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.update.SearchI.Filter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchI.Filter.toObject = function(includeInstance, msg) {
  var f, obj = {
    chunking: (f = msg.getChunking()) && proto.update.SearchI.Filter.Chunking.toObject(includeInstance, f),
    operatorList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    propertyList: jspb.Message.toObjectList(msg.getPropertyList(),
    proto.update.SearchI.Filter.Property.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.update.SearchI.Filter}
 */
proto.update.SearchI.Filter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.update.SearchI.Filter;
  return proto.update.SearchI.Filter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.update.SearchI.Filter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.update.SearchI.Filter}
 */
proto.update.SearchI.Filter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.update.SearchI.Filter.Chunking;
      reader.readMessage(value,proto.update.SearchI.Filter.Chunking.deserializeBinaryFromReader);
      msg.setChunking(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addOperator(value);
      break;
    case 3:
      var value = new proto.update.SearchI.Filter.Property;
      reader.readMessage(value,proto.update.SearchI.Filter.Property.deserializeBinaryFromReader);
      msg.addProperty(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.update.SearchI.Filter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.update.SearchI.Filter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.update.SearchI.Filter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchI.Filter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChunking();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.update.SearchI.Filter.Chunking.serializeBinaryToWriter
    );
  }
  f = message.getOperatorList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getPropertyList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.update.SearchI.Filter.Property.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.update.SearchI.Filter.Chunking.prototype.toObject = function(opt_includeInstance) {
  return proto.update.SearchI.Filter.Chunking.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.update.SearchI.Filter.Chunking} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchI.Filter.Chunking.toObject = function(includeInstance, msg) {
  var f, obj = {
    pointer: jspb.Message.getFieldWithDefault(msg, 1, ""),
    perpage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.update.SearchI.Filter.Chunking}
 */
proto.update.SearchI.Filter.Chunking.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.update.SearchI.Filter.Chunking;
  return proto.update.SearchI.Filter.Chunking.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.update.SearchI.Filter.Chunking} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.update.SearchI.Filter.Chunking}
 */
proto.update.SearchI.Filter.Chunking.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPointer(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPerpage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.update.SearchI.Filter.Chunking.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.update.SearchI.Filter.Chunking.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.update.SearchI.Filter.Chunking} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchI.Filter.Chunking.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPointer();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPerpage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string pointer = 1;
 * @return {string}
 */
proto.update.SearchI.Filter.Chunking.prototype.getPointer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.update.SearchI.Filter.Chunking} returns this
 */
proto.update.SearchI.Filter.Chunking.prototype.setPointer = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string perpage = 2;
 * @return {string}
 */
proto.update.SearchI.Filter.Chunking.prototype.getPerpage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.update.SearchI.Filter.Chunking} returns this
 */
proto.update.SearchI.Filter.Chunking.prototype.setPerpage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.update.SearchI.Filter.Property.prototype.toObject = function(opt_includeInstance) {
  return proto.update.SearchI.Filter.Property.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.update.SearchI.Filter.Property} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchI.Filter.Property.toObject = function(includeInstance, msg) {
  var f, obj = {
    timeline: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.update.SearchI.Filter.Property}
 */
proto.update.SearchI.Filter.Property.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.update.SearchI.Filter.Property;
  return proto.update.SearchI.Filter.Property.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.update.SearchI.Filter.Property} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.update.SearchI.Filter.Property}
 */
proto.update.SearchI.Filter.Property.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimeline(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.update.SearchI.Filter.Property.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.update.SearchI.Filter.Property.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.update.SearchI.Filter.Property} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchI.Filter.Property.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimeline();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional string timeline = 1;
 * @return {string}
 */
proto.update.SearchI.Filter.Property.prototype.getTimeline = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.update.SearchI.Filter.Property} returns this
 */
proto.update.SearchI.Filter.Property.prototype.setTimeline = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 timestamp = 2;
 * @return {number}
 */
proto.update.SearchI.Filter.Property.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.update.SearchI.Filter.Property} returns this
 */
proto.update.SearchI.Filter.Property.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional Chunking chunking = 1;
 * @return {?proto.update.SearchI.Filter.Chunking}
 */
proto.update.SearchI.Filter.prototype.getChunking = function() {
  return /** @type{?proto.update.SearchI.Filter.Chunking} */ (
    jspb.Message.getWrapperField(this, proto.update.SearchI.Filter.Chunking, 1));
};


/**
 * @param {?proto.update.SearchI.Filter.Chunking|undefined} value
 * @return {!proto.update.SearchI.Filter} returns this
*/
proto.update.SearchI.Filter.prototype.setChunking = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.update.SearchI.Filter} returns this
 */
proto.update.SearchI.Filter.prototype.clearChunking = function() {
  return this.setChunking(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.update.SearchI.Filter.prototype.hasChunking = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated string operator = 2;
 * @return {!Array<string>}
 */
proto.update.SearchI.Filter.prototype.getOperatorList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.update.SearchI.Filter} returns this
 */
proto.update.SearchI.Filter.prototype.setOperatorList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.update.SearchI.Filter} returns this
 */
proto.update.SearchI.Filter.prototype.addOperator = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.update.SearchI.Filter} returns this
 */
proto.update.SearchI.Filter.prototype.clearOperatorList = function() {
  return this.setOperatorList([]);
};


/**
 * repeated Property property = 3;
 * @return {!Array<!proto.update.SearchI.Filter.Property>}
 */
proto.update.SearchI.Filter.prototype.getPropertyList = function() {
  return /** @type{!Array<!proto.update.SearchI.Filter.Property>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.update.SearchI.Filter.Property, 3));
};


/**
 * @param {!Array<!proto.update.SearchI.Filter.Property>} value
 * @return {!proto.update.SearchI.Filter} returns this
*/
proto.update.SearchI.Filter.prototype.setPropertyList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.update.SearchI.Filter.Property=} opt_value
 * @param {number=} opt_index
 * @return {!proto.update.SearchI.Filter.Property}
 */
proto.update.SearchI.Filter.prototype.addProperty = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.update.SearchI.Filter.Property, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.update.SearchI.Filter} returns this
 */
proto.update.SearchI.Filter.prototype.clearPropertyList = function() {
  return this.setPropertyList([]);
};


/**
 * optional Filter filter = 1;
 * @return {?proto.update.SearchI.Filter}
 */
proto.update.SearchI.prototype.getFilter = function() {
  return /** @type{?proto.update.SearchI.Filter} */ (
    jspb.Message.getWrapperField(this, proto.update.SearchI.Filter, 1));
};


/**
 * @param {?proto.update.SearchI.Filter|undefined} value
 * @return {!proto.update.SearchI} returns this
*/
proto.update.SearchI.prototype.setFilter = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.update.SearchI} returns this
 */
proto.update.SearchI.prototype.clearFilter = function() {
  return this.setFilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.update.SearchI.prototype.hasFilter = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.update.SearchO.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.update.SearchO.prototype.toObject = function(opt_includeInstance) {
  return proto.update.SearchO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.update.SearchO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchO.toObject = function(includeInstance, msg) {
  var f, obj = {
    filter: (f = msg.getFilter()) && proto.update.SearchO.Filter.toObject(includeInstance, f),
    resultList: jspb.Message.toObjectList(msg.getResultList(),
    proto.update.SearchO.Result.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.update.SearchO}
 */
proto.update.SearchO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.update.SearchO;
  return proto.update.SearchO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.update.SearchO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.update.SearchO}
 */
proto.update.SearchO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.update.SearchO.Filter;
      reader.readMessage(value,proto.update.SearchO.Filter.deserializeBinaryFromReader);
      msg.setFilter(value);
      break;
    case 2:
      var value = new proto.update.SearchO.Result;
      reader.readMessage(value,proto.update.SearchO.Result.deserializeBinaryFromReader);
      msg.addResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.update.SearchO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.update.SearchO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.update.SearchO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilter();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.update.SearchO.Filter.serializeBinaryToWriter
    );
  }
  f = message.getResultList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.update.SearchO.Result.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.update.SearchO.Filter.prototype.toObject = function(opt_includeInstance) {
  return proto.update.SearchO.Filter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.update.SearchO.Filter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchO.Filter.toObject = function(includeInstance, msg) {
  var f, obj = {
    chunking: (f = msg.getChunking()) && proto.update.SearchO.Filter.Chunking.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.update.SearchO.Filter}
 */
proto.update.SearchO.Filter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.update.SearchO.Filter;
  return proto.update.SearchO.Filter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.update.SearchO.Filter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.update.SearchO.Filter}
 */
proto.update.SearchO.Filter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.update.SearchO.Filter.Chunking;
      reader.readMessage(value,proto.update.SearchO.Filter.Chunking.deserializeBinaryFromReader);
      msg.setChunking(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.update.SearchO.Filter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.update.SearchO.Filter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.update.SearchO.Filter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchO.Filter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChunking();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.update.SearchO.Filter.Chunking.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.update.SearchO.Filter.Chunking.prototype.toObject = function(opt_includeInstance) {
  return proto.update.SearchO.Filter.Chunking.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.update.SearchO.Filter.Chunking} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchO.Filter.Chunking.toObject = function(includeInstance, msg) {
  var f, obj = {
    pointer: jspb.Message.getFieldWithDefault(msg, 1, ""),
    perpage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.update.SearchO.Filter.Chunking}
 */
proto.update.SearchO.Filter.Chunking.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.update.SearchO.Filter.Chunking;
  return proto.update.SearchO.Filter.Chunking.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.update.SearchO.Filter.Chunking} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.update.SearchO.Filter.Chunking}
 */
proto.update.SearchO.Filter.Chunking.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPointer(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPerpage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.update.SearchO.Filter.Chunking.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.update.SearchO.Filter.Chunking.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.update.SearchO.Filter.Chunking} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchO.Filter.Chunking.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPointer();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPerpage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string pointer = 1;
 * @return {string}
 */
proto.update.SearchO.Filter.Chunking.prototype.getPointer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.update.SearchO.Filter.Chunking} returns this
 */
proto.update.SearchO.Filter.Chunking.prototype.setPointer = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string perpage = 2;
 * @return {string}
 */
proto.update.SearchO.Filter.Chunking.prototype.getPerpage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.update.SearchO.Filter.Chunking} returns this
 */
proto.update.SearchO.Filter.Chunking.prototype.setPerpage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Chunking chunking = 1;
 * @return {?proto.update.SearchO.Filter.Chunking}
 */
proto.update.SearchO.Filter.prototype.getChunking = function() {
  return /** @type{?proto.update.SearchO.Filter.Chunking} */ (
    jspb.Message.getWrapperField(this, proto.update.SearchO.Filter.Chunking, 1));
};


/**
 * @param {?proto.update.SearchO.Filter.Chunking|undefined} value
 * @return {!proto.update.SearchO.Filter} returns this
*/
proto.update.SearchO.Filter.prototype.setChunking = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.update.SearchO.Filter} returns this
 */
proto.update.SearchO.Filter.prototype.clearChunking = function() {
  return this.setChunking(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.update.SearchO.Filter.prototype.hasChunking = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.update.SearchO.Result.prototype.toObject = function(opt_includeInstance) {
  return proto.update.SearchO.Result.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.update.SearchO.Result} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchO.Result.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timeline: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.update.SearchO.Result}
 */
proto.update.SearchO.Result.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.update.SearchO.Result;
  return proto.update.SearchO.Result.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.update.SearchO.Result} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.update.SearchO.Result}
 */
proto.update.SearchO.Result.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimeline(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.update.SearchO.Result.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.update.SearchO.Result.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.update.SearchO.Result} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.update.SearchO.Result.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimeline();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.update.SearchO.Result.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.update.SearchO.Result} returns this
 */
proto.update.SearchO.Result.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string timeline = 2;
 * @return {string}
 */
proto.update.SearchO.Result.prototype.getTimeline = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.update.SearchO.Result} returns this
 */
proto.update.SearchO.Result.prototype.setTimeline = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 timestamp = 3;
 * @return {number}
 */
proto.update.SearchO.Result.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.update.SearchO.Result} returns this
 */
proto.update.SearchO.Result.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional Filter filter = 1;
 * @return {?proto.update.SearchO.Filter}
 */
proto.update.SearchO.prototype.getFilter = function() {
  return /** @type{?proto.update.SearchO.Filter} */ (
    jspb.Message.getWrapperField(this, proto.update.SearchO.Filter, 1));
};


/**
 * @param {?proto.update.SearchO.Filter|undefined} value
 * @return {!proto.update.SearchO} returns this
*/
proto.update.SearchO.prototype.setFilter = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.update.SearchO} returns this
 */
proto.update.SearchO.prototype.clearFilter = function() {
  return this.setFilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.update.SearchO.prototype.hasFilter = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Result result = 2;
 * @return {!Array<!proto.update.SearchO.Result>}
 */
proto.update.SearchO.prototype.getResultList = function() {
  return /** @type{!Array<!proto.update.SearchO.Result>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.update.SearchO.Result, 2));
};


/**
 * @param {!Array<!proto.update.SearchO.Result>} value
 * @return {!proto.update.SearchO} returns this
*/
proto.update.SearchO.prototype.setResultList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.update.SearchO.Result=} opt_value
 * @param {number=} opt_index
 * @return {!proto.update.SearchO.Result}
 */
proto.update.SearchO.prototype.addResult = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.update.SearchO.Result, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.update.SearchO} returns this
 */
proto.update.SearchO.prototype.clearResultList = function() {
  return this.setResultList([]);
};


goog.object.extend(exports, proto.update);
